#!/usr/bin/env bash
# THIS FILE IS GENERATED BY tools/setup_anaconda.sh
if [ -z "${PS1:-}" ]; then
    PS1=__dummy__
fi
. /home/t_yamamoto/workspace4/mmdetection3d/setup_venv/venv/etc/profile.d/conda.sh && conda deactivate && conda activate mmdet3d
